// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package dbgen

import (
	"database/sql"
)

type History struct {
	ID          int64          `json:"id"`
	PresetName  sql.NullString `json:"preset_name"`
	OutputPath  string         `json:"output_path"`
	SourceCount int64          `json:"source_count"`
	GeneratedAt int64          `json:"generated_at"`
}

type Preset struct {
	ID          int64          `json:"id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	CreatedAt   int64          `json:"created_at"`
	UpdatedAt   int64          `json:"updated_at"`
}

type PresetSource struct {
	PresetID int64 `json:"preset_id"`
	SourceID int64 `json:"source_id"`
}

type Source struct {
	ID         int64  `json:"id"`
	Name       string `json:"name"`
	SourceType string `json:"source_type"`
	Path       string `json:"path"`
	Content    string `json:"content"`
	Hash       string `json:"hash"`
	Enabled    int64  `json:"enabled"`
	CreatedAt  int64  `json:"created_at"`
	UpdatedAt  int64  `json:"updated_at"`
}
