// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: queries.sql

package dbgen

import (
	"context"
	"database/sql"
)

const addSourceToPreset = `-- name: AddSourceToPreset :exec
INSERT INTO preset_sources (preset_id, source_id)
VALUES (?, ?)
`

type AddSourceToPresetParams struct {
	PresetID int64 `json:"preset_id"`
	SourceID int64 `json:"source_id"`
}

func (q *Queries) AddSourceToPreset(ctx context.Context, arg AddSourceToPresetParams) error {
	_, err := q.db.ExecContext(ctx, addSourceToPreset, arg.PresetID, arg.SourceID)
	return err
}

const countEnabledSources = `-- name: CountEnabledSources :one
SELECT COUNT(*) FROM sources
WHERE enabled = 1
`

func (q *Queries) CountEnabledSources(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countEnabledSources)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countSources = `-- name: CountSources :one
SELECT COUNT(*) FROM sources
`

func (q *Queries) CountSources(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countSources)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createHistory = `-- name: CreateHistory :one

INSERT INTO history (preset_name, output_path, source_count)
VALUES (?, ?, ?)
RETURNING id, preset_name, output_path, source_count, generated_at
`

type CreateHistoryParams struct {
	PresetName  sql.NullString `json:"preset_name"`
	OutputPath  string         `json:"output_path"`
	SourceCount int64          `json:"source_count"`
}

// History
func (q *Queries) CreateHistory(ctx context.Context, arg CreateHistoryParams) (History, error) {
	row := q.db.QueryRowContext(ctx, createHistory, arg.PresetName, arg.OutputPath, arg.SourceCount)
	var i History
	err := row.Scan(
		&i.ID,
		&i.PresetName,
		&i.OutputPath,
		&i.SourceCount,
		&i.GeneratedAt,
	)
	return i, err
}

const createPreset = `-- name: CreatePreset :one

INSERT INTO presets (name, description)
VALUES (?, ?)
RETURNING id, name, description, created_at, updated_at
`

type CreatePresetParams struct {
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
}

// Presets
func (q *Queries) CreatePreset(ctx context.Context, arg CreatePresetParams) (Preset, error) {
	row := q.db.QueryRowContext(ctx, createPreset, arg.Name, arg.Description)
	var i Preset
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createSource = `-- name: CreateSource :one
INSERT INTO sources (name, source_type, path, content, hash, enabled)
VALUES (?, ?, ?, ?, ?, ?)
RETURNING id, name, source_type, path, content, hash, enabled, created_at, updated_at
`

type CreateSourceParams struct {
	Name       string `json:"name"`
	SourceType string `json:"source_type"`
	Path       string `json:"path"`
	Content    string `json:"content"`
	Hash       string `json:"hash"`
	Enabled    int64  `json:"enabled"`
}

func (q *Queries) CreateSource(ctx context.Context, arg CreateSourceParams) (Source, error) {
	row := q.db.QueryRowContext(ctx, createSource,
		arg.Name,
		arg.SourceType,
		arg.Path,
		arg.Content,
		arg.Hash,
		arg.Enabled,
	)
	var i Source
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.SourceType,
		&i.Path,
		&i.Content,
		&i.Hash,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteOldHistory = `-- name: DeleteOldHistory :exec
DELETE FROM history
WHERE generated_at < strftime('%s', 'now') - ?
`

func (q *Queries) DeleteOldHistory(ctx context.Context, dollar_1 interface{}) error {
	_, err := q.db.ExecContext(ctx, deleteOldHistory, dollar_1)
	return err
}

const deletePreset = `-- name: DeletePreset :exec
DELETE FROM presets
WHERE id = ?
`

func (q *Queries) DeletePreset(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deletePreset, id)
	return err
}

const deleteSource = `-- name: DeleteSource :exec
DELETE FROM sources
WHERE name = ?
`

func (q *Queries) DeleteSource(ctx context.Context, name string) error {
	_, err := q.db.ExecContext(ctx, deleteSource, name)
	return err
}

const deleteSourceByID = `-- name: DeleteSourceByID :exec
DELETE FROM sources
WHERE id = ?
`

func (q *Queries) DeleteSourceByID(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteSourceByID, id)
	return err
}

const getPreset = `-- name: GetPreset :one
SELECT id, name, description, created_at, updated_at FROM presets
WHERE id = ?
LIMIT 1
`

func (q *Queries) GetPreset(ctx context.Context, id int64) (Preset, error) {
	row := q.db.QueryRowContext(ctx, getPreset, id)
	var i Preset
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPresetByName = `-- name: GetPresetByName :one
SELECT id, name, description, created_at, updated_at FROM presets
WHERE name = ?
LIMIT 1
`

func (q *Queries) GetPresetByName(ctx context.Context, name string) (Preset, error) {
	row := q.db.QueryRowContext(ctx, getPresetByName, name)
	var i Preset
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPresetSources = `-- name: GetPresetSources :many
SELECT s.id, s.name, s.source_type, s.path, s.content, s.hash, s.enabled, s.created_at, s.updated_at FROM sources s
INNER JOIN preset_sources ps ON s.id = ps.source_id
WHERE ps.preset_id = ?
ORDER BY s.created_at ASC
`

func (q *Queries) GetPresetSources(ctx context.Context, presetID int64) ([]Source, error) {
	rows, err := q.db.QueryContext(ctx, getPresetSources, presetID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Source
	for rows.Next() {
		var i Source
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.SourceType,
			&i.Path,
			&i.Content,
			&i.Hash,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSource = `-- name: GetSource :one
SELECT id, name, source_type, path, content, hash, enabled, created_at, updated_at FROM sources
WHERE id = ?
LIMIT 1
`

func (q *Queries) GetSource(ctx context.Context, id int64) (Source, error) {
	row := q.db.QueryRowContext(ctx, getSource, id)
	var i Source
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.SourceType,
		&i.Path,
		&i.Content,
		&i.Hash,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSourceByHash = `-- name: GetSourceByHash :one
SELECT id, name, source_type, path, content, hash, enabled, created_at, updated_at FROM sources
WHERE hash = ?
LIMIT 1
`

func (q *Queries) GetSourceByHash(ctx context.Context, hash string) (Source, error) {
	row := q.db.QueryRowContext(ctx, getSourceByHash, hash)
	var i Source
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.SourceType,
		&i.Path,
		&i.Content,
		&i.Hash,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSourceByName = `-- name: GetSourceByName :one
SELECT id, name, source_type, path, content, hash, enabled, created_at, updated_at FROM sources
WHERE name = ?
LIMIT 1
`

func (q *Queries) GetSourceByName(ctx context.Context, name string) (Source, error) {
	row := q.db.QueryRowContext(ctx, getSourceByName, name)
	var i Source
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.SourceType,
		&i.Path,
		&i.Content,
		&i.Hash,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listEnabledSources = `-- name: ListEnabledSources :many
SELECT id, name, source_type, path, content, hash, enabled, created_at, updated_at FROM sources
WHERE enabled = 1
ORDER BY created_at ASC
`

func (q *Queries) ListEnabledSources(ctx context.Context) ([]Source, error) {
	rows, err := q.db.QueryContext(ctx, listEnabledSources)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Source
	for rows.Next() {
		var i Source
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.SourceType,
			&i.Path,
			&i.Content,
			&i.Hash,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHistory = `-- name: ListHistory :many
SELECT id, preset_name, output_path, source_count, generated_at FROM history
ORDER BY generated_at DESC
LIMIT ?
`

func (q *Queries) ListHistory(ctx context.Context, limit int64) ([]History, error) {
	rows, err := q.db.QueryContext(ctx, listHistory, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []History
	for rows.Next() {
		var i History
		if err := rows.Scan(
			&i.ID,
			&i.PresetName,
			&i.OutputPath,
			&i.SourceCount,
			&i.GeneratedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPresets = `-- name: ListPresets :many
SELECT id, name, description, created_at, updated_at FROM presets
ORDER BY created_at DESC
`

func (q *Queries) ListPresets(ctx context.Context) ([]Preset, error) {
	rows, err := q.db.QueryContext(ctx, listPresets)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Preset
	for rows.Next() {
		var i Preset
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSources = `-- name: ListSources :many
SELECT id, name, source_type, path, content, hash, enabled, created_at, updated_at FROM sources
ORDER BY created_at DESC
`

func (q *Queries) ListSources(ctx context.Context) ([]Source, error) {
	rows, err := q.db.QueryContext(ctx, listSources)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Source
	for rows.Next() {
		var i Source
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.SourceType,
			&i.Path,
			&i.Content,
			&i.Hash,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeSourceFromPreset = `-- name: RemoveSourceFromPreset :exec
DELETE FROM preset_sources
WHERE preset_id = ? AND source_id = ?
`

type RemoveSourceFromPresetParams struct {
	PresetID int64 `json:"preset_id"`
	SourceID int64 `json:"source_id"`
}

func (q *Queries) RemoveSourceFromPreset(ctx context.Context, arg RemoveSourceFromPresetParams) error {
	_, err := q.db.ExecContext(ctx, removeSourceFromPreset, arg.PresetID, arg.SourceID)
	return err
}

const updateSourceContent = `-- name: UpdateSourceContent :exec
UPDATE sources
SET content = ?,
    hash = ?,
    updated_at = strftime('%s', 'now')
WHERE id = ?
`

type UpdateSourceContentParams struct {
	Content string `json:"content"`
	Hash    string `json:"hash"`
	ID      int64  `json:"id"`
}

func (q *Queries) UpdateSourceContent(ctx context.Context, arg UpdateSourceContentParams) error {
	_, err := q.db.ExecContext(ctx, updateSourceContent, arg.Content, arg.Hash, arg.ID)
	return err
}

const updateSourceEnabled = `-- name: UpdateSourceEnabled :exec
UPDATE sources
SET enabled = ?,
    updated_at = strftime('%s', 'now')
WHERE name = ?
`

type UpdateSourceEnabledParams struct {
	Enabled int64  `json:"enabled"`
	Name    string `json:"name"`
}

func (q *Queries) UpdateSourceEnabled(ctx context.Context, arg UpdateSourceEnabledParams) error {
	_, err := q.db.ExecContext(ctx, updateSourceEnabled, arg.Enabled, arg.Name)
	return err
}
