// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package dbgen

import (
	"context"
)

type Querier interface {
	AddSourceToPreset(ctx context.Context, arg AddSourceToPresetParams) error
	CountEnabledSources(ctx context.Context) (int64, error)
	CountSources(ctx context.Context) (int64, error)
	// History
	CreateHistory(ctx context.Context, arg CreateHistoryParams) (History, error)
	// Presets
	CreatePreset(ctx context.Context, arg CreatePresetParams) (Preset, error)
	CreateSource(ctx context.Context, arg CreateSourceParams) (Source, error)
	DeleteOldHistory(ctx context.Context, dollar_1 interface{}) error
	DeletePreset(ctx context.Context, id int64) error
	DeleteSource(ctx context.Context, name string) error
	DeleteSourceByID(ctx context.Context, id int64) error
	GetPreset(ctx context.Context, id int64) (Preset, error)
	GetPresetByName(ctx context.Context, name string) (Preset, error)
	GetPresetSources(ctx context.Context, presetID int64) ([]Source, error)
	GetSource(ctx context.Context, id int64) (Source, error)
	GetSourceByHash(ctx context.Context, hash string) (Source, error)
	GetSourceByName(ctx context.Context, name string) (Source, error)
	ListEnabledSources(ctx context.Context) ([]Source, error)
	ListHistory(ctx context.Context, limit int64) ([]History, error)
	ListPresets(ctx context.Context) ([]Preset, error)
	ListSources(ctx context.Context) ([]Source, error)
	RemoveSourceFromPreset(ctx context.Context, arg RemoveSourceFromPresetParams) error
	UpdateSourceContent(ctx context.Context, arg UpdateSourceContentParams) error
	UpdateSourceEnabled(ctx context.Context, arg UpdateSourceEnabledParams) error
}

var _ Querier = (*Queries)(nil)
